modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="ytgld" #optional
description='''
.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #optional
    modId="chest_item" #mandatory
    type="required" #mandatory
    versionRange="[1.21.1-1.2.2.8,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
